### ISSUE TITLE
'whatwg-fetch' issues

### ISSUE THREAD

**Issue by cemorell** [generalassembly-atx/movies_lab#1]
Have rm -rf d 4 different repositories and downloaded the npms in several ways. Still throwing this error

```
ERROR in ./src/components/movie-container.js
Module not found: Error: Cannot resolve module 'whatwg-fetch' in /Users/Camille/Desktop/GA/homework/week8/project/movies_lab/src/components
 @ ./src/components/movie-container.js 13:0-23
```

**Comment by changamanda** [comment]
Are you trying to use the `fetch` function?

If so, did you `npm install whatwg-fetch --save` and `import 'whatwg-fetch';`? https://github.com/github/fetch
