### ISSUE TITLE
getting an array of objects with movies in it, but it isnt liking our map function to go through them.

### ISSUE THREAD

**Issue by rpreilley** [generalassembly-atx/movies_lab#2]
We are console logging our results and it is showing our object of movies that is an array of objects, but when we try to iterate through them and put them on the page it states there is a parsing issue. We did something similar to the walkthrough yesterday but it isnt functioning.

<img width="763" alt="screen shot 2016-07-22 at 10 34 02 am" src="https://cloud.githubusercontent.com/assets/17994022/17062323/22bdfe64-4ff8-11e6-88bb-5c819f2727cd.png">
<img width="503" alt="screen shot 2016-07-22 at 10 34 15 am" src="https://cloud.githubusercontent.com/assets/17994022/17062321/22ba0ef8-4ff8-11e6-9ebf-8b348475827d.png">
<img width="1159" alt="screen shot 2016-07-22 at 10 34 25 am" src="https://cloud.githubusercontent.com/assets/17994022/17062322/22bca956-4ff8-11e6-9f38-0ffcf8aa4618.png">

**Comment by changamanda** [comment]
Console.log`this.props.movies` between lines 8 and 9 of the MovieList file? What gets logged?

**Comment by rpreilley** [comment]
an empty array

**Comment by rpreilley** [comment]
so i see that being a problem, that its trying to iterate through an empty array.. but when we console.log the results in our container, its showing us the object with an array of movie objects.

**Comment by rpreilley** [comment]
it is empty at first, but when we search for something, it console.logs again with the object that has the array.

**Comment by changamanda** [comment]
So you're trying to iterate through an object, not the array that is inside of it. You'll need to extract the _array_ from that object and save it to `this.state.movies` in the container, so that `this.props.movies` in the list is an array instead of an object.

**Comment by rpreilley** [comment]
We got it. We didnt realize the API is case sensitive, so appending search instead of Search to our results.
