### ISSUE TITLE
Map is undefined

### ISSUE THREAD

**Issue by lilixiaoxx** [generalassembly-atx/movies_lab#4]
ReactDOM.js:75Download the React DevTools for a better development experience: https://fb.me/react-devtools
movie-container.js:28 undefined
movie-container.js:34 parsing failed TypeError: Cannot read property 'map' of undefined(…)

```
import React from 'react';
import 'whatwg-fetch';
import MovieSearch from './movie-search';
import MovieList from './movie-list'


class MovieContainer extends React.Component {
  constructor(props){
    super(props);
    this.state={
      movie:[]
    }
  }


  componentWillMount() {
    this._fetchMovie();
  }

_fetchMovie(searchTerm) {

    if (searchTerm) {
      fetch(`//www.omdbapi.com/?t=${searchTerm}`)
      .then((response) => {
        return response.json()
      })
      .then((results) => {
        console.log(results.Search);
        this.setState({
         movie: results.Search
        })
      })
      .catch((ex) => {
        console.log('parsing failed', ex)
      })
  }
}

  render(){
    return (<div>
      <MovieSearch search={this._fetchMovie.bind(this)}/>
      <MovieList movie={this.state.movie}/>
    </div>)
  }
}

export default MovieContainer;
```

**Comment by changamanda** [comment]
What is your `MovieList` file?

**Comment by lilixiaoxx** [comment]
```import React from 'react';
import Movie from './movie';

class MovieList extends React.Component {
  constructor(props){
    super(props);
  }
  render(){
    return (
      <div>
      {this.props.movie.map((movie, i) => { return (<Movie key={i} {...movie} />); }) }
      </div>
    );
  }
}

export default MovieList;

```
```

**Comment by changamanda** [comment]
Put a debugger here:

```
render(){
debugger
return (
  {this.props.movie.map((movie, i) => { return (); }) }
);
}
}
```

Then inspect `this.props.movie` after a search. What gets logged? Try to inspect `this.props.movie` twice, because the first one might be empty.

**Comment by changamanda** [comment]
I notice two things that could potentially be breaking it:

```
  componentWillMount() {
    this._fetchMovie();
  }
```

As soon as the container is rendered on the page, you're doing a search with probably an empty term and getting this response: [http://www.omdbapi.com/?t=](http://www.omdbapi.com/?t=)

Also, you'll want to query the search endpoint since you're dealing with lists. Change your URL to //www.omdbapi.com/?**s**=${searchTerm}

**Comment by lilixiaoxx** [comment]
we did the second one ,and we got a huge object

**Comment by changamanda** [comment]
Yup, but you already have code for it: `movie: results.Search`
`Search` is a key in the search (s) endpoint, not the title (t) endpoint

In any case, you'll want to make sure `this.props.movie` is an array; that's what the error ultimately is saying

**Comment by changamanda** [comment]
I'll check in with you again after lunch if it's still not working! 🎉

**Comment by lilixiaoxx** [comment]
we got it:)
