### ISSUE TITLE
trying to have plot only show on an event listener.

### ISSUE THREAD

**Issue by rpreilley** [generalassembly-atx/movies_lab#5]
I am trying to have the plot show up only if you click a line that is rendered that says click here for plot but seem to be having some issues. I think were close, and I referred back to how we did that with the reveal image react homework. I set the initial state for the plot and have it to where if it exists after querying the API, which it does, to then render to the page. What am I missing?

<img width="783" alt="screen shot 2016-07-22 at 2 37 10 pm" src="https://cloud.githubusercontent.com/assets/17994022/17069012/d8f5100c-5019-11e6-83ce-4b7e8ef9074a.png">

**Comment by rpreilley** [comment]
I feel like I am close.. When I click on the click here line it does console log the plot of that movie.

**Comment by changamanda** [comment]
Explain that conditional to me? Below `console.log(results.Plot);`. I think that's your problem.

**Comment by rpreilley** [comment]
when i console.log results.Plot, when i click that part thats rendered it console.logs the plot

**Comment by rpreilley** [comment]
i did just test this.state though and it is undefined on console. so thats why the conditional wasnt working. i think?

**Comment by rpreilley** [comment]
im trying to have the conditional say that if it sees that there is a plot, to render it when that line is clicked, otherwise dont show a plot at all

**Comment by rpreilley** [comment]
This is what I have now. Sorry, I know I'm blowing this thread up haha.

<img width="812" alt="screen shot 2016-07-22 at 2 46 55 pm" src="https://cloud.githubusercontent.com/assets/17994022/17069244/2f462ca6-501b-11e6-9709-8b3930c28fe5.png">

**Comment by rpreilley** [comment]
Changed <p> { results.Plot }</p> back to this.state.plot because it breaks otherwise

**Comment by rpreilley** [comment]
in the paragraph tag in the return

**Comment by changamanda** [comment]
`results.Plot` is right, I think, because otherwise you're just setting `this.state.plot` equal to what `this.state.plot` already is. What was the error?

**Comment by rpreilley** [comment]
<img width="952" alt="screen shot 2016-07-22 at 2 52 11 pm" src="https://cloud.githubusercontent.com/assets/17994022/17069380/ef245480-501b-11e6-9479-addcd67cc53b.png">

**Comment by changamanda** [comment]
Maybe it's a scope thing?

Try:

```
if (currentPlot){
  var newPlot = results.Plot;
  console.log(newPlot);
  this.setState({plot: newPlot});
}
```

**Comment by changamanda** [comment]
What gets logged?

**Comment by rpreilley** [comment]
same thing. says results is not defined.. but im confused as to why, when I clicked on it it console.logged results.Plot and it shows me the plot. not sure how its not defined.
